version: '3.9'


services:
  node-js:
    # Debe llamarse productividad-api
    container_name: productividad-api
    build: .
    # archivo .env es .env.test
    
    environment:
      - PORT=5000
    ports:
      - 5020:5000
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/health", "||", "exit", "1"]
      interval: 5s
      timeout: 2s
      retries: 3
    networks:
      - app-network
    links:
      - db
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:5.7
    container_name: productividad-db
    hostname: mysql
    environment:
      - MYSQL_DATABASE=${DOCKER_DATABASE}
      - MYSQL_USER=${DOCKER_DB_USER}
      - MYSQL_PASSWORD=rootPass#123
      - MYSQL_ROOT_PASSWORD=${DOCKER_DB_PASSWORD}
    ports:
      # <Port exposed> : <MySQL Port>
      - 3308:${DOCKER_DB_PORT}
    volumes:
      - db_storage:/var/lib/mysql
      - ./src/main/resources/db/init.sql:/data/application/init.sql
    networks:
      - app-network
    healthcheck:
      # test for mysql service startup
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
networks:
  app-network:
    driver: bridge
    
volumes:
  db_storage: